version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"    

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend